version: "3.7"

services:
    database:
        image: mysql:5.7
        volumes:
            - database_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: sml12345
            MYSQL_DATABASE: wordpress
            MYSQL_USER: ubuntu
            MYSQL_PASSWORD: sml12345

    wordpress:
        image: wordpress:latest
        depends_on:
            - database
        ports:
            - 8080:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_USER: ubuntu
            WORDPRESS_DB_PASSWORD: sml12345
        volumes:
            - .wordpress/plugins:/var/www/html/wp-content/plugins
            - .wordpress/themes:/var/www/html/wp-content/themes
            - .wordpress/uploads:/var/www/html/wp-content/uploads
volumes:
    database_data:
